name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to production
    runs-on: curatorial-production
    env:
        CURATORIAL_DIR: ${{ secrets.CURATORIAL_DIR }}
    steps:
    - name: Pull changes
      shell: bash
      run: |
        cd $CURATORIAL_DIR
        git pull
    - name: Update dependencies
      shell: bash
      run: |
        cd $CURATORIAL_DIR
        php composer.phar install --optimize-autoloader --no-dev
    - name: Update cache and database
      shell: bash
      run: |
        cd $CURATORIAL_DIR
        php artisan key:generate
        php artisan migrate
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        php artisan permission:cache-reset
        echo "Don't forget to run 'php artisan db:seed PermissionSeeder if needed!"
