name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test (Laravel)
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.3'
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Setup environment
      run: |
        php artisan key:generate --env=testing
        chmod -R 777 storage bootstrap/cache
    - name: Create database
      run: |
        touch tests/database.sqlite
        php artisan migrate --env=testing
        php artisan db:seed PermissionSeeder --env=testing
    - name: Run tests
      run: php artisan test --env=testing
